# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pichaza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Travel', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Nairobi', max_length=20),
        ),
    ]
