# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pichaza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(default='NO IMAGE', upload_to='pichazza/'),
        ),
    ]
