# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pichaza', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_location',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pichaza.Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
