# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pichaza', '0003_auto_20180929_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
    ]
